# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2.1

orbs:
    lambda-dev: lambda-dev/dev-release-1@0.0.1

jobs:
  build:
    docker: 
      - image: "circleci/node:8"
    steps:
      - run:
          name: "Env variables"
          command: |
                  echo 'export LAMBDATEST_USERNAME="deepakm"' >> $BASH_ENV
                  echo 'export LT_ACCESS_KEY="gIUJGTZtydrnSbdGro6Hm0yOJDfFBJWGZQ8FdyPA1rv07ZxxQA"' >> $BASH_ENV
                  echo 'export LT_USERNAME="deepakm"' >> $BASH_ENV
                  echo 'export LAMBDATEST_EMAIL="deepakm@lambdatest.com"' >> $BASH_ENV
                  echo 'export LAMBDATEST_KEY="gIUJGTZtydrnSbdGro6Hm0yOJDfFBJWGZQ8FdyPA1rv07ZxxQA"' >> $BASH_ENV

workflows:      
    Execute-Orbs:
      jobs:
        
        - lambda-dev/with_tunnel:
            steps:
              - run: # test what branch we're on.
                  name: "Here is the LT_Username : "
                  command: echo ${LT_USERNAME}       

              - run: 
                  command: |
                    npm install
                    node_modules/.bin/nightwatch -e chrome


